"""
Streamlit App — Used Car Price Predictor
Run with: streamlit run app/app.py

This is a lightweight, interactive front-end for the trained pricing
model, similar in spirit to how a real listings platform would let a
seller enter their car's details and get an instant price estimate.
"""

import streamlit as st
import pandas as pd
import joblib
import os

st.set_page_config(page_title="Used Car Price Predictor", page_icon="🚗", layout="centered")

MODEL_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "best_model.pkl")

@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)

model = load_model()

st.title("🚗 Used Car Price Predictor")
st.caption("A CARS24-inspired project — estimate a fair resale price for a used car based on its condition, age, and market factors.")

st.divider()

col1, col2 = st.columns(2)

with col1:
    brand = st.selectbox("Brand", ["Maruti Suzuki", "Hyundai", "Tata", "Honda", "Toyota",
                                    "Mahindra", "Kia", "Ford", "Volkswagen", "Renault"])
    city = st.selectbox("City", ["Delhi NCR", "Mumbai", "Bengaluru", "Pune", "Hyderabad",
                                  "Chennai", "Kolkata", "Ahmedabad", "Jaipur", "Chandigarh"])
    car_age = st.slider("Car Age (years)", 0, 15, 5)
    km_driven = st.number_input("KM Driven", min_value=0, max_value=300000, value=45000, step=1000)
    fuel_type = st.selectbox("Fuel Type", ["Petrol", "Diesel", "CNG", "Electric"])

with col2:
    transmission = st.selectbox("Transmission", ["Manual", "Automatic"])
    owner_count = st.selectbox("Number of Previous Owners", [1, 2, 3, 4])
    mileage_kmpl = st.slider("Mileage (kmpl)", 4.0, 30.0, 18.0)
    engine_cc = st.selectbox("Engine (cc)", [800, 1000, 1197, 1199, 1498, 1997, 2000, 2200])
    insurance_valid = st.selectbox("Insurance Valid?", ["Yes", "No"])

st.divider()

if st.button("🔍 Predict Price", use_container_width=True):
    km_per_year = km_driven / max(car_age, 1)

    input_df = pd.DataFrame([{
        "brand": brand, "city": city, "car_age": car_age, "km_driven": km_driven,
        "fuel_type": fuel_type, "transmission": transmission, "owner_count": owner_count,
        "mileage_kmpl": mileage_kmpl, "engine_cc": engine_cc,
        "insurance_valid": insurance_valid, "km_per_year": km_per_year,
    }])

    predicted_price = model.predict(input_df)[0]

    st.success(f"### Estimated Selling Price: ₹ {predicted_price:,.0f}")
    st.caption("This estimate is generated by an XGBoost regression model trained on 6,000 synthetic used-car listings. "
               "In a production setting, this would be trained on real historical transaction data.")

st.divider()
st.caption("Built as a portfolio project demonstrating an end-to-end ML pipeline for a used-car pricing use case.")
