"""
run_queries.py
---------------
Loads car_listings.csv + dim_city.csv into an in-memory SQLite database
and executes every query in analysis_queries.sql, saving results as
Markdown tables (for the README) and printing them to console.
"""

import sqlite3
import pandas as pd
import re
import os

os.makedirs("sql/query_outputs", exist_ok=True)

conn = sqlite3.connect(":memory:")

listings = pd.read_csv("data/car_listings.csv")
dim_city = pd.read_csv("data/dim_city.csv")
listings.to_sql("car_listings", conn, index=False, if_exists="replace")
dim_city.to_sql("dim_city", conn, index=False, if_exists="replace")

with open("sql/analysis_queries.sql") as f:
    sql_text = f.read()

# split into individual queries on the "-- Q<n>." markers
blocks = re.split(r"-- Q\d+\.", sql_text)
headers = re.findall(r"-- (Q\d+\..*?)\n", sql_text)
queries = [b.strip().rstrip(";").strip() + ";" for b in blocks[1:]]

md_report = ["# SQL Analysis — Query Outputs\n",
             "Generated by `sql/run_queries.py` against the synthetic CARS24-style listings dataset.\n"]

for header, query in zip(headers, queries):
    # keep only lines from the first real SQL keyword onward, dropping any
    # leftover comment/description lines above it
    lines = query.splitlines()
    start_idx = next(
        (i for i, l in enumerate(lines) if re.match(r"^\s*(WITH|SELECT)\b", l, re.IGNORECASE)),
        0,
    )
    clean_query = "\n".join(
        l for l in lines[start_idx:] if not l.strip().startswith("--")
    ).strip()

    print(f"\n{'='*70}\n{header}\n{'='*70}")
    result = pd.read_sql_query(clean_query, conn)
    print(result.to_string(index=False))

    md_report.append(f"\n## {header}\n")
    md_report.append(result.to_markdown(index=False))
    md_report.append("\n")

    safe_name = header.split(".")[0].strip().replace(" ", "_")
    result.to_csv(f"sql/query_outputs/{safe_name}.csv", index=False)

with open("sql/query_outputs/README.md", "w") as f:
    f.write("\n".join(md_report))

print("\n\nAll query outputs saved to sql/query_outputs/")
conn.close()
